import { EmploymentType, LanguageCode, SeniorityLevel, WorkArrangement } from '@prisma/client';
import type { RawJob } from './job-source.types';

/**
 * Curated, realistic sample Israeli job postings for development and testing.
 * These are fictional listings (not scraped) so the platform can be exercised
 * end-to-end before real, compliant source integrations are added.
 */
export const SEED_JOBS: RawJob[] = [
  {
    externalId: 'seed-001',
    title: 'Senior Backend Engineer',
    company: 'TelAviv Cloud Ltd',
    description:
      'Build scalable microservices in Node.js and TypeScript on AWS. Own services end-to-end, mentor engineers, and design for high throughput with PostgreSQL and Redis.',
    location: 'Tel Aviv-Yafo',
    city: 'Tel Aviv',
    isRemote: false,
    workArrangement: WorkArrangement.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.SENIOR,
    salaryMin: 32000,
    salaryMax: 45000,
    language: LanguageCode.EN,
    skills: ['System design', 'Mentoring'],
    technologies: ['node.js', 'typescript', 'postgresql', 'redis', 'aws', 'docker'],
    postedAt: new Date('2026-07-10'),
  },
  {
    externalId: 'seed-002',
    title: 'Frontend Engineer (React)',
    company: 'Herzliya Fintech',
    description:
      'Develop a modern React + Next.js web app with TypeScript and TailwindCSS. Care about performance, accessibility, and full RTL Hebrew support.',
    location: 'Herzliya',
    city: 'Herzliya',
    isRemote: false,
    workArrangement: WorkArrangement.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.MID,
    salaryMin: 24000,
    salaryMax: 34000,
    language: LanguageCode.EN,
    skills: ['Communication'],
    technologies: ['react', 'next.js', 'typescript', 'tailwind', 'css', 'html'],
    postedAt: new Date('2026-07-12'),
  },
  {
    externalId: 'seed-003',
    title: 'מפתח/ת Full Stack',
    company: 'ירושלים בריאות דיגיטלית',
    description:
      'פיתוח מערכת בריאות דיגיטלית עם React בצד לקוח ו-Node.js בצד שרת. עבודה מול PostgreSQL, סביבת ענן ומתודולוגיית Agile. נדרש ניסיון בפיתוח פולסטאק.',
    location: 'ירושלים',
    city: 'Jerusalem',
    isRemote: false,
    workArrangement: WorkArrangement.ONSITE,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.MID,
    salaryMin: 22000,
    salaryMax: 30000,
    language: LanguageCode.HE,
    skills: ['Agile'],
    technologies: ['react', 'node.js', 'postgresql', 'typescript'],
    postedAt: new Date('2026-07-11'),
  },
  {
    externalId: 'seed-004',
    title: 'DevOps Engineer',
    company: 'Haifa Infrastructure Systems',
    description:
      'Own CI/CD, Kubernetes clusters, and Terraform infrastructure on GCP. Improve observability and reliability across services.',
    location: 'Haifa',
    city: 'Haifa',
    isRemote: true,
    workArrangement: WorkArrangement.REMOTE,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.SENIOR,
    salaryMin: 34000,
    salaryMax: 46000,
    language: LanguageCode.EN,
    skills: ['System design'],
    technologies: ['kubernetes', 'terraform', 'docker', 'gcp', 'linux', 'git'],
    postedAt: new Date('2026-07-09'),
  },
  {
    externalId: 'seed-005',
    title: 'Data Scientist',
    company: 'Beer Sheva AI Labs',
    description:
      'Build and deploy machine-learning models with Python, PyTorch, and pandas. Work on NLP for Hebrew and English text.',
    location: "Be'er Sheva",
    city: "Be'er Sheva",
    isRemote: false,
    workArrangement: WorkArrangement.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.MID,
    salaryMin: 28000,
    salaryMax: 40000,
    language: LanguageCode.EN,
    skills: ['System design'],
    technologies: ['python', 'pytorch', 'pandas', 'sql'],
    postedAt: new Date('2026-07-08'),
  },
  {
    externalId: 'seed-006',
    title: 'Product Manager',
    company: 'Raanana SaaS',
    description:
      'Lead product discovery and delivery for a B2B SaaS platform. Define roadmap, work with design and engineering, and drive outcomes.',
    location: "Ra'anana",
    city: "Ra'anana",
    isRemote: false,
    workArrangement: WorkArrangement.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.SENIOR,
    salaryMin: 30000,
    salaryMax: 42000,
    language: LanguageCode.EN,
    skills: ['Project management', 'Communication'],
    technologies: [],
    postedAt: new Date('2026-07-07'),
  },
  {
    externalId: 'seed-007',
    title: 'Cyber Security Analyst',
    company: 'Tel Aviv SecureNet',
    description:
      'Monitor and respond to security incidents, run threat analysis, and harden cloud infrastructure. No academic degree required — hands-on experience valued.',
    location: 'Tel Aviv-Yafo',
    city: 'Tel Aviv',
    isRemote: false,
    workArrangement: WorkArrangement.ONSITE,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.JUNIOR,
    salaryMin: 20000,
    salaryMax: 30000,
    language: LanguageCode.EN,
    skills: ['Communication'],
    technologies: ['linux', 'aws', 'python'],
    postedAt: new Date('2026-07-13'),
  },
  {
    externalId: 'seed-008',
    title: 'iOS Mobile Developer',
    company: 'Netanya Mobile Studio',
    description:
      'Build native iOS apps in Swift. Collaborate with product and design to ship delightful mobile experiences.',
    location: 'Netanya',
    city: 'Netanya',
    isRemote: true,
    workArrangement: WorkArrangement.REMOTE,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.MID,
    salaryMin: 26000,
    salaryMax: 36000,
    language: LanguageCode.EN,
    skills: [],
    technologies: ['git'],
    postedAt: new Date('2026-07-06'),
  },
  {
    externalId: 'seed-009',
    title: 'QA Automation Engineer',
    company: 'Petah Tikva QualityWorks',
    description:
      'Design and maintain automated test suites for web and API. Work closely with developers to ensure release quality.',
    location: 'Petah Tikva',
    city: 'Petah Tikva',
    isRemote: false,
    workArrangement: WorkArrangement.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.JUNIOR,
    salaryMin: 18000,
    salaryMax: 26000,
    language: LanguageCode.EN,
    skills: ['Communication'],
    technologies: ['typescript', 'git'],
    postedAt: new Date('2026-07-05'),
  },
  {
    externalId: 'seed-010',
    title: 'מנהל/ת שיווק דיגיטלי',
    company: 'תל אביב מדיה',
    description:
      'ניהול קמפיינים דיגיטליים, אסטרטגיית תוכן ובקרת ביצועים. נדרשת יכולת ניהול צוות, תקשורת בין-אישית מצוינת וניסיון בשיווק דיגיטלי.',
    location: 'תל אביב',
    city: 'Tel Aviv',
    isRemote: false,
    workArrangement: WorkArrangement.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    seniority: SeniorityLevel.MANAGER,
    salaryMin: 22000,
    salaryMax: 32000,
    language: LanguageCode.HE,
    skills: ['Team leadership', 'Communication'],
    technologies: [],
    postedAt: new Date('2026-07-04'),
  },
];
