import { z } from 'zod';

/**
 * Personalized, human-readable explanation of a single job match, generated by
 * a lightweight LLM over the deterministic/semantic scores. Surfaced on demand
 * (e.g. an "explain this match" action) rather than precomputed for every match.
 */
export interface MatchInsight {
  /** Short, warm explanation of why the candidate fits (Hebrew, 1–2 sentences). */
  whyYouFit: string;
  /** What is missing or worth strengthening (Hebrew, 1 sentence). */
  whatYouMiss: string;
  /** Name of the AI provider that produced the insight. */
  provider: string;
}

/** Schema the LLM's JSON output must satisfy (before we attach `provider`). */
export const matchInsightSchema = z.object({
  whyYouFit: z.string().min(1).max(600),
  whatYouMiss: z.string().min(1).max(400),
});
